"use strict";
exports.__esModule = true;
var cadena_1 = require("./cadena");
var num_1 = require("./num");
var cadena;
var numero;
cadena = new cadena_1.Cadena("sé verlas al revés ");
console.log("-------------------Prueba de la clase cadena ----------------------------");
console.log("La cadena: ", cadena.text);
console.log(" Es palindromo: ", cadena.palindromo);
console.log(" Numero de vocales: ", cadena.vocales);
console.log(" Numero de palabras: ", cadena.palabras);
console.log(" Numero de letras: ", cadena.letras);
console.log("-------------------Prueba de la clase numero ----------------------------");
numero = new num_1.Numero(7);
console.log("El numero: ", numero.valor);
console.log("Sumado con 10", numero.sumar(10));
console.log("Restando con 10", numero.resta(10));
console.log("Factorial: ", numero.factorial(numero.valor));
console.log("Es primo: ", numero.primo);
